first_name = Label(frame, text="First Name", font=("cambria 15 bold"), bg='red', fg="black").place(x=100, y=50)
fir_name_entry = Entry(frame, width=15, font=("cambria 15"))
fir_name_entry.place(x=100, y=80)
fir_name_entry.focus()
last_name = Label(frame, text="Last Name", font=("cambria 15 bold"), bg="red", fg="black").place(x=310, y=50)
last_name_entry = Entry(frame, width=15, font=("cambria 15"))
last_name_entry.place(x=310, y=80)
father_name = Label(frame, text="Father Name", font=("cambria 15 bold"), bg="red", fg="black").place(x=100, y=120)
fathr_name_entry = Entry(frame, width=15, font=("cambria 15"))
fathr_name_entry.place(x=100, y=150)
mother_name = Label(frame, text="Mother Name", font=("cambria 15 bold"), bg="red", fg="black").place(x=310, y=120)
mther_name_entry = Entry(frame, width=15, font=("cambria 15"))
mther_name_entry.place(x=310, y=150)
dob = Label(frame, text="DOB", font=("cambria 15 bold"), bg="red", fg="black").place(x=100, y=200)
dob_entry = Entry(frame, width=15, font=("cambria 15 bold"))
dob_entry.place(x=100, y=230)
contact = Label(frame, text="Roll No", font=("cambria 15 bold"), bg="red", fg="black").place(x=310, y=200)
cont_entry = Entry(frame, width=15, font=("cambria 15 bold"))
cont_entry.place(x=310, y=230)
email = Label(frame, text="Email", font=("cambria 15 bold"), bg="red", fg="black").place(x=100, y=280)
email_entry = Entry(frame, width=15, font=("cambria 15 bold"))
email_entry.place(x=100, y=310)
address = Label(frame, text="Address", font=("cambria 15 bold"), bg="red", fg="black").place(x=310, y=280)
addrs_entry = Entry(frame, width=15, font=("cambria 15 bold"))
addrs_entry.place(x=310, y=310)
vehicle = Label(frame, text="Vehicle No.", font=("cambria 15 bold"), bg="red", fg="black").place(x=100, y=350)
vehicle_entry = Entry(frame, width="15", font=("cambria 15 bold"))
vehicle_entry.place(x=100, y=390)
work_place = Label(frame, text="Work Place/College", font=("cambria 15 bold"), bg="red", fg="black").place(x=310, y=350)
place_entry = Entry(frame, width="15", font=("cambria 15 bold"))
place_entry.place(x=310, y=390)
gender = Label(frame, text="Gender", font=("cambria 15 bold"), bg="red", fg="black").place(x=100, y=420)